### PR TITLE
[ENH] PDF Reports

### PR DESCRIPTION
**Pull request by oesteban**
This PR adds the feature of writing a PDF report per subject and per run (group report) plotting the QC measures and some additional information (for examples, see attached documents).

The reporting works as a hook after execution of all subject-wise workflows. It works iff there's a CSV file created in the output folder. Finally, an additional tool `scripts/qap_reports.py` can be used to generate reports "offline". However, if the workflow was run with  `write_report: False` the mosaic plots and FD plots will not be available.

Description of changes:
- **Visualization files** - a new module `qap.viz` has been created. It includes three submodules: 
  - `reports.py` were the final appearance of reports is generated,
  - `plotting.py` in which the actual plots are written using seaborn, and
  - `interfaces.py` in which there are two new nipype interfaces to plotting utilities.
  - Additionally, there's a html folder with the documentation that is appended to each report.
- **Pipelines affected** (under `scripts/`): qap_anatomical_spatial.py, qap_functional_temporal.py and qap_functional_spatial.py:
  - The pipelines are modified to include checking the new setting `write_report: True` in the config.yml file. The setting can also be enabled using the flag `--with-reports`, even though its use is discouraged.
  - The internal pipelines implementing each subject `build_*` have been slightly modified, as well as the actual pipelines living in `qap_workflows.py`. The actual pipelines are modified to write all the results to the same CSV file, using the `AddCSVRow` interface of nipype. The functional-temporal workflow has also been added a tSNR calculator from nipype.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
This is the corresponding documentation: https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/pull/20

**Comment by oesteban** [comment]
Please, let me rebase to current master.

**Comment by oesteban** [comment]
Something is not correctly merged: the tests passed but did not generate the reports. However `write_report` is `True`. I'll check on this as soon as possible.

**Comment by chrisgorgo** [comment]
Good catch!

**Comment by sgiavasis** [comment]
@oesteban Heads up, when I run the pipelines, it's having trouble importing the viz subpackage, despite the existence of the **init**.py.

It does not see it at all, even when I attempt to manually do an absolute import from the Python interpreter. I can't tell what's causing it to be "invisible".

Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/qap-1.0.4-py2.7.egg/qap/cli.py", line 396, in _build_workflow
    workflow, resource_pool = wf_builder(workflow, resource_pool, config)
  File "/usr/local/lib/python2.7/dist-packages/qap-1.0.4-py2.7.egg/qap/qap_workflows.py", line 359, in qap_functional_spatial_workflow
    from qap.viz.interfaces import PlotMosaic
ImportError: No module named viz.interfaces

**Comment by chrisgorgo** [comment]
Maybe your development environment is not configured correctly. Try
uninstalling the package using pip and rely only on PYTHONPATH.

**Comment by sgiavasis** [comment]
It does run when I do that - though it's happening to an end user as well after she installed via pip - so something is missing somewhere in the process.

**Comment by oesteban** [comment]
Maybe we have missed to add 'qap.viz' in the packages key of setup.py ? (https://docs.python.org/2/distutils/examples.html#pure-python-distribution-by-package).

**Comment by chrisgorgo** [comment]
Does this replicate in a fresh visualenv?

**Comment by oesteban** [comment]
I have reported this bug in #26 and #27 fixed it in a fresh virtualenv.

**Comment by sgiavasis** [comment]
@oesteban , revisiting this PR- we may not be including tSNR as a quality metric, as far as I know, so we might roll that addition back. Please let me know if there was any discussion/impetus about adding it that I missed.

**Comment by ccraddock** [comment]
Please remove tSNR, it isn't an appropriate measure for human data for a variety of reasons. Primarily the "noise" is actually the signal and making any decisions by optimizing this measure will by definition reduce BOLD variation. A better measure of tSNR for task based data would the ratio of modeled variance over residual variance (an f-test). Since it is very difficult to differentiate signal from noise variance in resting state, it is impossible to define tSNR in this context. Perhaps it could be measured from residual variance over modeled variance from the nuisance regression step, but this would by definition prefer poorer noise models, which is bad news. fALFF has been used to estimate quality of rsfMRI data, to some effect, but it is very sensitive to TR, and thus hard to compare across different acquisition strategies. 

We will include signal-to-fluctuation noise ratio (SFNR) to the phantom package of QAP when we implement that.

**Pull request merged**
