### PR TITLE
Merge the QAP transition to pipeline - QAP 1.0

### PR DESCRIPTION
**Pull request by sgiavasis**

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Looks very exciting! Cannot wait to dig in. Any chance for an updated user guide? @craigmoodie have a look at this.

**Comment by sgiavasis** [comment]
Hi Chris!

Here's the user guide we've got going so far:
https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/blob/www/index.md

A test suite and developer documentation is following.

Cheers!

**Comment by craigmoodie** [comment]
Excellent! This will be very useful for our pipeline.

**Comment by chrisgorgo** [comment]
Thanks! I recommend CircleCI.com for running continious integration tests
on real data.

**Comment by craigmoodie** [comment]
Cool, that's the one you recommended to Shea as well right?



Can I ask you a nipype question?


I'm trying to pull two file inputs using SelectFiles and then combining them as MapNode inputs with the output of a different node in a downstream customized function node. However, nipype is putting both files from SelectFiles as the input of the first field, so I get the following error:


ValueError: All iterfields of a MapNode have to have the same length.



Any way I can easily resolve this?



Best,

Craig.


--

Craig Moodie

Postdoctoral Fellow

Poldrack Lab

Department of Psychology

Stanford University.




________________________________

**Comment by jpellman** [comment]
Hi @chrisfilo ,

The user guide has also been pushed to the gh-pages repo now, so you should be able to read it here as well:
http://preprocessed-connectomes-project.github.io/quality-assessment-protocol/

**Pull request merged**
