### PR TITLE
Updates to the QAP Documentation

### PR DESCRIPTION
**Pull request by craigmoodie**
This PR should update the online documentation to provide users with information about the new report functionality which is being sent in a separate PR.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
As a side note: the "failing" tests are due to the fact that no tests are defined in the gh-pages branch. This can be ignored. In the future we should add some dummy circle.yml file in this branch.

**Comment by jpellman** [comment]
Could you do a PR for the markdown files too?  We're storing those on the 'www' branch.

**Comment by chrisgorgo** [comment]
Why is this in two places? Is the HTML in the GH pages generated from the
www branch?

**Comment by jpellman** [comment]
Hi Chris,

We use Jekyll to generate the documentation from the markdown files contained in the www branch.  When the HTML has been generated in the _site folder, we switch to the gh-pages branch (where _site is untracked) and copy the generated HTML files to the main site.

**Comment by chrisgorgo** [comment]
Ok I see. I guess we should've gotten in touch with you before editing the HTML pages. My bad!

Could you describe the procedure of editing the www branch and using jekyll to update the gh-branch? Preferably on a github wiki page so future devs could benefit from it. This way @craigmoodie will be able to transfer his changes to markdown and send a PR to the www branch and check if everything renders correctly.

PS In the future we should consider merging master and www branches.

**Comment by jpellman** [comment]
Sure- here are the steps we've been using to generate the docs:

https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/wiki/Updating-the-Documentation-for-QAP

**Comment by chrisgorgo** [comment]
Thanks!

**Comment by craigmoodie** [comment]
I have now update this branch by first updating the markdown files in the "www" branch. We don't have an automatic CircleCI test for either branch, but can you please still review the PR to see if the updates to online documentation are acceptable?

**Comment by jpellman** [comment]
Hi Craig,

There were a couple small aesthetic changes that I made to the markdown files in the 'www' branch (i.e., moving the documentation on _write_report_ to the _Pipeline Configuration YAML Files_ with the other YAML options, providing a hyperlink to the command usage section for qap_*.py instead of repeating it, removing the list of workflows that reports functionality was implemented in because it looks like it was implemented in all of them) but otherwise the docs have been updated on the 'gh-pages' branch.

One thing I'm a little unclear on is how in [paragraph 3 of Generating Reports](http://preprocessed-connectomes-project.github.io/quality-assessment-protocol/#generating-reports) the group-level reports option is toggled.  Does there need to be another key-value pair for the YAML config, or is there something else I'm missing?

--John

**Comment by craigmoodie** [comment]
Hi John,

Thanks for looking the PRs over and making those aesthetic improvements. The "write_report: True" option in the config YAML is the only option for individual and group reports. Is that the source of confusion? If so, I can clarify that in the documentation.

Please let me know how you would like to proceed.

Best,
Craig.

On Oct 30, 2015, at 2:07 PM, John Pellman <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Craig,

There were a couple small aesthetic changes that I made to the markdown files in the 'www' branch (i.e., moving the documentation on write_report to the Pipeline Configuration YAML Files with the other YAML options, providing a hyperlink to the command usage section for qap_*.py instead of repeating it, removing the list of workflows that reports functionality was implemented in because it looks like it was implemented in all of them) but otherwise the docs have been updated on the 'gh-pages' branch.

One thing I'm a little unclear on is how in paragraph 3 of Generating Reportshttp://preprocessed-connectomes-project.github.io/quality-assessment-protocol/#generating-reports the group-level reports option is toggled. Does there need to be another key-value pair for the YAML config, or is there something else I'm missing?

--John

##

**Comment by jpellman** [comment]
Hi Craig,

The way I read it, there were two toggles in the YAML file for writing reports- one for individual-level reports, and one for the group-level report.  What tripped me up was the 'In addition, you have the option' phrase at the beginning of the third paragraph.  Maybe it would would be less ambiguous to say something like 'Group-level reports with plots of all the various metrics that contain scores aggregated from all scans/individuals per metric are also generated and stored in qap_functional_spatial.pdf' or something similar?

**Comment by craigmoodie** [comment]
Hi John,
I agree that the rewording you suggested would be more clear. Would you like to make the changes in the original repo or for me to push them?

**Comment by jpellman** [comment]
Hi Craig,

If you could make the changes on your fork and then do a PR to 'www'/'gh-pages' that would be fine.

**Comment by jpellman** [comment]
Hi Craig,

The markdown files that you would need to edit for this and any other updates are now just in the 'gh-pages' branch (which GitHub automatically renders into HTML).

**Comment by jpellman** [comment]
Hi Craig and Chris,

We've found a way to store the markdown files for the documentation on the main page and then deploy them to the gh-pages branch using Travis, so we're going to move towards that.  That way, any time that we make changes to the master branch we can also edit the documentation and have it pushed to gh-pages without having to switch branches.

**Comment by craigmoodie** [comment]
Hi John,

do you need us to change the MD files in any way in order for the Travis transition to occur?

**Comment by jpellman** [comment]
Hi Craig,

The content of the markdown files is unaffected.  The only change is that
you'll need to store them within a 'docs' directory on the master branch
rather than on 'gh-pages' itself.  'gh-pages' will contain HTML files
rendered by Jekyll.

2015-11-19 14:27 GMT-05:00 craigmoodie notifications@github.com:

**Pull request closed without merging**
