### PR TITLE
[FIX] PDF reports missing code after merge

### PR DESCRIPTION
**Pull request by oesteban**
This PR adds the simple code that was lost during merge of #21 .

The pdf reports were not generated. To check for this (and see some examples of report), please see the corresponding "Artifacts tab" in CircleCI (https://circleci.com/gh/oesteban/quality-assessment-protocol/96#artifacts).

### CODE REVIEW

**Comment by chrisgorgo** [comment]
So what happened during the merge?

**Comment by sgiavasis** [comment]
I'm not sure - I'm going to double check.

**Comment by oesteban** [comment]
Since I merged the body of all the workflows in the new file `cli.py`, git did not see the conflict and the merge was smooth (ignoring the modifications in the `scripts/qap_*.py` workflows for generating PDF files).

**Comment by chrisgorgo** [comment]
Indeed weird - @sgiavasis did you merge on github or manually on your
machine?

**Comment by sgiavasis** [comment]
I merged manually- but that conflict did not pop up in the auto-merge.

**Pull request merged**
